name: Check XRay

on:
  pull_request:
    paths:
        - "Migrators/XRayExporter/**"
env:
  XRAY_DIR: ./Migrators/XRayExporter


jobs:

  xray_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win-x64
            artifact_name: XRayExporter.exe
            asset_name: XRayExporter-win-x64-TEST.exe
          - os: linux-x64
            artifact_name: XRayExporter
            asset_name: XRayExporter-linux-x64-TEST
          # - os: osx-x64
          #   artifact_name: XRayExporter
          #   asset_name: XRayExporter-osx-x64-TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.XRAY_DIR }}
        
      - name: Publish project
        run: |
          dotnet publish \
          -r ${{ matrix.os }} \
          --configuration Release \
          --self-contained true \
          --output ./publish \
          --no-restore ${{ env.XRAY_DIR }} 
             
