name: Check TestLink

on:
  pull_request:
    paths:
        - "Migrators/TestLinkExporter/**"
env:
  TESTLINK_DIR: ./Migrators/TestLinkExporter


jobs:
 
  testlink_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win-x64
            artifact_name: TestLinkExporter.exe
            asset_name: TestLinkExporter-win-x64-TEST.exe
          - os: linux-x64
            artifact_name: TestLinkExporter
            asset_name: TestLinkExporter-linux-x64-TEST
          # - os: osx-x64
          #   artifact_name: TestLinkExporter
          #   asset_name: TestLinkExporter-osx-x64-TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.TESTLINK_DIR }}
        
      - name: Publish project
        run: |
          dotnet publish \
          -r ${{ matrix.os }} \
          --configuration Release \
          --self-contained true \
          --output ./publish \
          --no-restore ${{ env.TESTLINK_DIR }} 
                          
