name: Check HPALM

on:
  pull_request:
    paths:
        - "Migrators/HPALMExporter/**"
env:
  HPALM_DIR: ./Migrators/HPALMExporter

jobs:
               
  hpalm_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win-x64
            artifact_name: HPALMExporter.exe
            asset_name: HPALMExporter-win-x64-TEST.exe
          - os: linux-x64
            artifact_name: HPALMExporter
            asset_name: HPALMExporter-linux-x64-TEST
          # - os: osx-x64
          #   artifact_name: HPALMExporter
          #   asset_name: HPALMExporter-osx-x64-TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.HPALM_DIR }}
        
      - name: Publish project
        run: |
          dotnet publish \
          -r ${{ matrix.os }} \
          --configuration Release \
          --self-contained true \
          --output ./publish \
          --no-restore ${{ env.HPALM_DIR }} 
                
  