name: Check Allure

on:
  pull_request:
    paths:
        - "Migrators/AllureExporter/**"
        - "Migrators/JsonWriter/**"
        - "Migrators/Models/**"
env:
  ALLURE_DIR: ./Migrators/AllureExporter


jobs:
  
  allure_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win-x64
            artifact_name: AllureExporter.exe
            asset_name: AllureExporter-win-x64-TEST.exe
          - os: linux-x64
            artifact_name: AllureExporter
            asset_name: AllureExporter-linux-x64-TEST
          # - os: osx-x64
          #   artifact_name: AllureExporter
          #   asset_name: AllureExporter-osx-x64-TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.ALLURE_DIR }}
        
      - name: Publish project
        run: |
          dotnet publish \
          -r ${{ matrix.os }} \
          --configuration Release \
          --self-contained true \
          --output ./publish \
          --no-restore ${{ env.ALLURE_DIR }} 
       