name: Release validate

on:
  pull_request

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"project\":[\"Importer\",\"AllureExporter\",\"AzureExporter\",\"ZephyrScaleExporter\",\"ZephyrScaleServerExporter\",\"ZephyrSquadExporter\",\"ZephyrSquadServerExporter\",\"XRayExporter\",\"TestCollabExporter\",\"TestLinkExporter\",\"TestRailExporter\",\"TestRailXmlExporter\",\"PractiTestExporter\",\"SpiraTestExporter\",\"HPALMExporter\",\"QaseExporter\"]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      fail-fast: true
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    uses: ./.github/workflows/build-project.yml
    with:
      project_path: ./Migrators/${{ matrix.project }}
      runtime: win-x64
