name: Release

on:
  release:
    types: [released]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"project\":[\"Importer\",\"AllureExporter\",\"AzureExporter\",\"ZephyrScaleExporter\",\"ZephyrScaleServerExporter\",\"ZephyrSquadExporter\",\"ZephyrSquadServerExporter\",\"XRayExporter\",\"TestCollabExporter\",\"TestLinkExporter\",\"TestRailExporter\",\"TestRailXmlExporter\",\"PractiTestExporter\",\"SpiraTestExporter\",\"HPALMExporter\",\"QaseExporter\"],\"os\":[\"win-x64\",\"linux-x64\",\"osx-x64\"]}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      fail-fast: true
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    uses: ./.github/workflows/build-project.yml
    with:
      project_path: ./Migrators/${{ matrix.project }}
      runtime: ${{ matrix.os }}

  upload:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Set artifact names
        id: artifacts
        run: |
          if [ "${{ matrix.os }}" = "win-x64" ]; then
            echo "artifact_name=${{ matrix.project }}.exe" >> $GITHUB_OUTPUT
            echo "asset_name=${{ matrix.project }}-${{ matrix.os }}-${{ github.event.release.tag_name }}.exe" >> $GITHUB_OUTPUT
          else
            echo "artifact_name=${{ matrix.project }}" >> $GITHUB_OUTPUT
            echo "asset_name=${{ matrix.project }}-${{ matrix.os }}-${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: publish/${{ steps.artifacts.outputs.artifact_name }}
          asset_name: ${{ steps.artifacts.outputs.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
