name: Validate TestCollab Tests

on:
  pull_request:
    paths:
      - "Migrators/TestCollabExporterTests/**"
      - "Migrators/TestCollabExporter/**"

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yaml
    with:
      project_path: ./Migrators/TestCollabExporterTests
