name: Validate TestLink Tests

on:
  pull_request:
    paths:
      - "Migrators/TestLinkExporterTests/**"
      - "Migrators/TestLinkExporter/**"

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yaml
    with:
      project_path: ./Migrators/TestLinkExporterTests
