name: Validate Azure Tests

on:
  pull_request:
    paths:
      - "Migrators/AzureExporterTests/**"
      - "Migrators/AzureExporter/**"

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yaml
    with:
      project_path: ./Migrators/AzureExporterTests
